# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='insta/')),
                ('name', models.CharField(max_length=30)),
                ('image_Caption', models.CharField(max_length=50)),
                ('post', tinymce.models.HTMLField()),
                ('likes', models.CharField(max_length=40)),
                ('Comments', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.CharField(max_length=40)),
                ('bio', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instagram.Profile'),
        ),
    ]
